name: test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test_job:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: cat python hello.py
